### ISSUE TITLE
Consider erroring if response object has an error key

### ISSUE THREAD

**Issue by iamdustan** [redux-effects/redux-effects-fetch#1]
Would you be open to throwing to an error status if a given `json` response has an `error` key? Something like the following chained onto the end of the fetch `then`s:

```
function checkErrorKey (maybeJson) {
  if (maybeJson.error) throw maybeJson.error;
  return maybeJson;
}
```

**Comment by ashaffer** [comment]
I would suggest making a middleware for that.  This is where this approach really shines, your middleware has absolute power to do stuff like this for you:

```javascript
function fetchErrors () {
  return next => action =>
    action.type === 'FETCH'
      ? next(action).then(res => res.hasOwnProperty(error) ? Promise.reject(res) : res)
      : next(action)
}
```

Is that a satisfactory solution for you?

**Comment by iamdustan** [comment]
Where would that go in the middleware chain? Since the `redux-effects-fetch` middleware handles that action.type and doesn’t `next` it I don’t have the opportunity to do it afterward. `redux-effects-fetch` middleware also handles the entire response deconstruction so I’d need to implement all of that to manage that.

The other more verbose/decentralized alternative I can think of would be to have every `fetch` call handle this unwrapping in it’s sucess meta.step handler.

**Comment by iamdustan** [comment]
ah! nvm. Since it calls next on the action, it passes the middleware on to the `redux-effects-fetch` middleware and then captures the response.

brilliant. Thanks!

**Comment by ashaffer** [comment]
You'd put it before redux-effects-fetch in the middleware chain.

**Comment by ashaffer** [comment]
Ah great :)
