### ISSUE TITLE
Updating Readme.md

### ISSUE THREAD

**Issue by dyong0** [redux-effects/redux-effects-fetch#15]
I would like to propose to write redux-effects-fetch uses isomorphic-fetch. I've felt nervous like 'hmm.. it may use fetch of es6. is it ok for any browsers? (after opening the source code) oh, great! Redux-effects-fetch takes isomorphic-fetch!'

**Comment by ashaffer** [comment]
Updated the readme. It's on the top line now :). Thx for pointing that out.

**Comment by dyong0** [comment]
My pleasure. :)
