### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by gsinovsky** [redux-effects/redux-effects-fetch#16]
When using this library alongside React Native v0.31.0-rc.1 I get `Can't find variable: self` on the debugger and the android log says 

``` ash
E/ReactNativeJS( 6043): Can't find variable: self
W/ReactNativeJS( 6043): Unable to symbolicate stack trace: undefined is not a function (evaluating 'fetch(devServer.url+'symbolicate',{
W/ReactNativeJS( 6043): method:'POST',
W/ReactNativeJS( 6043): body:JSON.stringify({stack:stack})})')
E/ReactNativeJS( 6043): Module AppRegistry is not a registered callable module.
W/ReactNativeJS( 6043): Unable to symbolicate stack trace: undefined is not a function (evaluating 'fetch(devServer.url+'symbolicate',{
W/ReactNativeJS( 6043): method:'POST',
W/ReactNativeJS( 6043): body:JSON.stringify({stack:stack})})')
```

I think is somewhat related to [this](https://github.com/facebook/react-native/issues/5667), yet I haven't been able to fix it, any ideas?

**Comment by ashaffer** [comment]
I'm not sure, from your links it looks like an issue with React Native itself, though nobody seems to be responding to it.

**Comment by gsinovsky** [comment]
You can close this now, is an issue related to [this](https://github.com/facebook/react-native/issues/9605)
