### ISSUE TITLE
Question: composing fetches?

### ISSUE THREAD

**Issue by iamdustan** [redux-effects/redux-effects-fetch#3]
I am currently looking for a way to fire off numerous fetches and have them bound to a single set of error/success handlers.

```js
// standard Promises and browser fetch
var a = fetch('http://www.some.api/resource');
var b = fetch('http://www.another.api/resource');

return Promise.all([a, b]).then(success, failure);
```

```js
// something like this maybe hopefully with bind-effects and effects-fetch?
bind(
  [fetch('http://www.some.api/resource'),
   fetch('http://www.another.api/resource')],
  onSuccess,
  onError
);
```

**Comment by ashaffer** [comment]
Right now the best way to do that would be:

```javascript
function () {
  return [
    bind(fetch('http://www.some.api/resource'), onSuccess, onError),
    bind(fetch('http://www.another.api/resource'), onSuccess, onError)
  ]
}
```

However, I have been thinking about changing the `.forEach` in [redux-multi](https://github.com/ashaffer/redux-multi) to a `.map`, and then allowing redux-effects to `Promise.all` on arrays like that.  I think that might be able to address your problem more cleanly?

**Comment by ashaffer** [comment]
Alright, I have updated redux-effects, bind-effect, and redux-multi.  Now effect composition is a first-class action - `EFFECT_COMPOSE` and redux-multi returns its array.  You should now be able to do exactly what you wanted:

```javascript
bind(
  [fetch('http://www.some.api/resource'),
   fetch('http://www.another.api/resource')],
  onSuccess,
  onError
);
```

Let me know if you run into any issues, but closing for now :).

**Comment by iamdustan** [comment]
Nice! That was quicker than I had a chance to even come back to this. Thanks @ashaffer!
