### ISSUE TITLE
Return the response object as part of the result

### ISSUE THREAD

**Issue by leoasis** [redux-effects/redux-effects-fetch#8]
I'm particularly thinking about the response status, which may be useful to handle the response (is it a 401, a 422 or a 500?), but perhaps some other information about the response could be handy for different use cases.

**Comment by ashaffer** [comment]
You're right.  Let me think about this a bit.  My reason for not doing that is that I would really like the callback to be pure.  I.e. not interacting with non-deterministic things like promises or other stateful entities.  Perhaps we can simply do the deserialization and then do something like `{headers, body, status}`, where each of those three are plain objects.

Thoughts?

**Comment by leoasis** [comment]
Yeah I agree that the API should not expose something that users would be tempted to use in a way that causes side effects, as this is the main goal of this library to remove.

I agree on doing the deserialization here and just provide the data as plain object properties. For that I suggest to provide the same properties of the request as are provided in elm-http: https://github.com/evancz/elm-http/blob/master/src/Http.elm#L273-L279

**Comment by ashaffer** [comment]
Just pushed this.  Thanks for pointing this out.

**Comment by leoasis** [comment]
Awesome stuff, thank you for working on it!
